# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: |
          (?x)(
              ^example/large/file.csv|
              ^example/large/sklearn-model.pkl
          )
      - id: requirements-txt-fixer
      - id: detect-private-key

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.4.5
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [
          'dbt-snowflake==1.3.0',
          'sqlfluff-templater-dbt==1.4.5'
        ]
      - id: sqlfluff-fix
        stages: [manual]  # this command is available only to run manually
        additional_dependencies: [
          'dbt-snowflake==1.3.0',
          'sqlfluff-templater-dbt==1.4.5'
        ]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.2.0
    hooks:
      - id: dbt-docs-generate
        # - id: check-source-table-has-description
        # - id: check-model-columns-have-desc
        # - id: check-model-has-all-columns
      - id: check-model-has-tests
        args: ["--test-cnt", "2", "--"]
